apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pvc
  labels:
    type: local
spec:
  storageClassName: ''
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/minio-pvc"
