apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-claim
  labels:
    type: local
spec:
  storageClassName: ''
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-pv-claim"
