apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../base
  - namespace.yaml
images:
  - name: kubeflow/training-operator
    newName: registry.cn-shenzhen.aliyuncs.com/leechen/training-training-operator
    newTag: "760ac1171dd30039a7363ffa03c77454bd714da5"
